services:
  # app:
  #   build: .
  #   container_name: micro-videos-admin
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/app

  db:
    image: mysql:8.0.30-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined
